---
name: qte_thesis
channels: [conda-forge, r, nodefaults]
dependencies:
  - python ==3.12
  - pip >=21.1
  - openjdk

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask >=0.5.0
  - pytask-latex >=0.4.2
  - pytask-parallel >=0.5.0
  - dask[distributed] >=2024.5.0     # Dask scheduler/workers
  - dask-jobqueue >=0.8.5            # Slurm integration
  - python-dotenv >=1.0.1   
  - pytest
  - pytest-cov
  - pytest-xdist

  # Python template project dependencies
  - statsmodels
  - numpy
  - pandas >=2.2
  - plotly >=5.2.0

  # Project specific solvers
  - cvxpy
  - scipy


  # Install project

  - pip:
      - -e .
      - pdbp
      - kaleido
      
  

